### ISSUE TITLE
HDBSCAN example

### ISSUE THREAD

**Issue by hadronzoo** [jean-pierreBoth/annembed#6]
The project has an HDBSCAN module with no exported functions. Could you incorporate HDBSCAN clustering into one of the examples?

**Comment by jean-pierreBoth** [comment]
In fact the module hdbscan is only a beginning and i was diverted into
another path. Hope i will complete that one day

Le mar. 7 mai 2024 à 06:35, Joshua Griffith ***@***.***> a
écrit :

**Comment by hadronzoo** [comment]
I understand. Thank you for your response and for open sourcing this library.
